{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "external-secrets.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }}
