apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "external-secrets.fullname" . }}-env-var
  namespace: {{ template "external-secrets.namespace" . }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  {{- with .Values.upstream.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  EXTERNAL_SECRETS_NAMESPACE: {{ .Values.env.EXTERNAL_SECRETS_NAMESPACE | quote }}